stages:
  - quality
  - integration

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

default:
  interruptible: true

quality:
  stage: quality
  image: docker:29-cli
  variables:
    DOCKER_HOST: ''
  script:
    - docker compose -f ci/compose.yaml run --build --rm quality

integration:
  stage: integration
  image: docker:29-cli
  variables:
    DOCKER_HOST: ''
  script:
    - docker compose -f ci/compose.yaml run --build --rm integration
  after_script:
    - docker compose -f ci/compose.yaml down --volumes --remove-orphans
