[project]
name = "working_time"
authors = [
    { name = "ALYF GmbH", email = "hallo@alyf.de" },
    { name = "Jonas Jakob IT & InfoSec (JITIS)", email = "info@jitis.io" }
]
maintainers = [
    { name = "Jonas Jakob IT & InfoSec (JITIS)", email = "info@jitis.io" }
]
description = "Project-centred time tracking and billing preparation for ERPNext"
requires-python = ">=3.11"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
dynamic = ["version"]
dependencies = [
    # frappe -- https://github.com/frappe/frappe is installed via 'bench init'
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
hrms = ">=16.0.0,<17.0.0"

[tool.ruff]
line-length = 110
target-version = "py311"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "E101", # indentation contains mixed spaces and tabs
    "E402", # module level import not at top of file
    "E501", # line too long
    "W191", # indentation contains tabs
]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

[project.urls]
Homepage = "https://github.com/jitis-io/working-time"
Repository = "https://github.com/jitis-io/working-time"
"Bug Reports" = "https://github.com/jitis-io/working-time/issues"
