name: Generate Semantic Release
on:
  push:
    branches:
      - version-16
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec @saithodev/semantic-release-gitea --no-save
      - name: Create Release
        env:
          GITEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITEA_URL: ${{ github.server_url }}
          GIT_AUTHOR_NAME: "alyf-linus"
          GIT_AUTHOR_EMAIL: "136631072+alyf-linus@users.noreply.github.com"
          GIT_COMMITTER_NAME: "alyf-linus"
          GIT_COMMITTER_EMAIL: "136631072+alyf-linus@users.noreply.github.com"
        run: npx semantic-release